[2223] Exception filters code is emitted incorrectly if there are several catch sections (#2244)
* [2223] Exception filters code is emitted incorrectly if there are several catch sections

* [2223] Update client test output

* [2223] Use constants instead of hardcoded strings; add XML comment on new method Script.SafeFunc; formatted cs to remove redundant whitespaces; adding client tests always identify with issue number;

* [2223] Amend xml doc for Script.SafeFunc

* [2223] Fix Travis error Utils/Roslyn/LocalUsageGatherer.cs(141,31): error CS0414: Warning as Error: The private field `Bridge.Translator.IdentifierReplacer._semanticModel' is assigned but its value is never used